%compile me
function compile_command_gui_test
%exec_env_var='';%optional shell env var to be cleared.
include_files = {'/cm/shared/workstation_code_dev/recon/CS_v2/agilent2glusterspaceCS.m' ...
    '/cm/shared/workstation_code_dev/recon/CS_v2/load_fid_hdrCS.m' ... 
    '/cm/shared/workstation_code_dev/recon/CS_v2/readprocparCS.m' ...
    '/cm/shared/workstation_code_dev/recon/CS_v2/gui_info_collect.m' ...    
    '/cm/shared/workstation_code_dev/recon/CS_v2/puller_glusterspaceCS.m'
    };%optional, but required if using exec_env_var, can be empty.
compile_command__allpurpose('gui_test_exec.m',include_files);%,exec_env_var);
